### ISSUE TITLE
Webcam remains active despite closing out of an exercise page

### ISSUE THREAD

**Issue by jilinzheng** [AI-Coach-PT/ExerSights#40] opened 2024-10-22 18:17 UTC
Webcam shows still in use after leaving the exercise page to another page, say, home or catalog; my guess is the useEffect calling detectPose must have a return statement that closes the webcam...

**Comment by jilinzheng** [comment] 2024-10-22 18:21
https://github.com/google-ai-edge/mediapipe/issues/1408#issuecomment-810652766

**Comment by Anish701** [comment] 2024-10-24 16:09
I tried to include a return in the useEffect to unmount and stop the webcam, but this did not solve the issue. The only fix that did work, however, was forcing a full page reload whenever the user clicks on a different page in the menubar. However, this is not that efficient for rendering.

Force full page reload in Menubar.js:
`<Button color="inherit" onClick={() => window.location.href = '/home'}>
      Home
  </Button>`
  
  Code to unmount and stop webcam in SquatPage.js useEffect (did not solve the bug):
  `
  useEffect(() => {
    detectPose(webcamRef, canvasRef, processPoseResults);

    // Cleanup function to stop the webcam when component is unmounted
    return () => {
        if (webcamRef.current && webcamRef.current.video && webcamRef.current.video.srcObject) {
            const stream = webcamRef.current.video.srcObject;
            const tracks = stream.getTracks();
            tracks.forEach(track => track.stop());  // Stop all tracks to release camera
        }
    };
}, []);
  `

**Comment by jilinzheng** [comment] 2024-10-24 18:42
I wonder if it is possible to instantiate the Camera object in the useEffect() on the page that calls detectPose(), then pass the Camera object to PoseDetector for it to call the camera.start() function; that way, in the parent page with the useEffect(), it becomes possible to stop the camera with the camera.stop() function.

Also I'm not sure if it is related, but as I am working on my other issue with Firebase, the camera latency progressively gets worse. My guess is that the camera never gets shut off, so on each iteration I go into the page and/or open/close the settings modal, detectPose is getting called, and never 'freed', making the performance worse and worse over time.

**Comment by Anish701** [comment] 2024-10-27 20:51
I think it is an issue with the legacy Pose model. This repo (https://github.com/HerbertShin/Hand-Tracking-React-App/tree/master) has the same issue as us. However, our branch which uses the new tasks-vision model does not have this bug.

**Comment by Anish701** [comment] 2024-10-27 23:15
I am confident that the cause of this error is within PoseDetecor.js in the detectPose method, specifically in this section:
`if (webcamRef.current && typeof webcamRef.current.video !== "undefined") {
        const camera = new Camera(webcamRef.current.video, {
            onFrame: async () => {
                if (webcamRef.current && webcamRef.current.video) {
                    await pose.send({ image: webcamRef.current.video });
                }
            },
            width: 640,
            height: 480,
        });
        camera.start();
    }`
Initializing the MediaPipe camera module results in the React webcam not shutting down even after the page has been exited. I tried to stop streaming and also tried camera.stop(), but the issue continued to persist.

Other repositories I found which use the legacy Pose model have the same issue. Feel free to take a try at solving this, but none of the fixes I tried worked. I propose 2 solutions for resolving this bug:
**Solution #1**
Commit to using the new tasks-vision model as this does not result in the bug. See PR (https://github.com/AI-Coach-PT/ExerSights/pull/54)

**Solution #2**
Keep the legacy pose model on the table, but force a re-render every time the user leave an exercise page. The entire app must be re-rendered to shut off the webcam. As mentioned in a prior comment: Force full page reload in Menubar.js by using window.location.href rather than Link react-router component:
<Button color="inherit" onClick={() => window.location.href = '/home'}> Home </Button>

**Closed** 2024-10-30 21:48 UTC
Labels: bug, help wanted, critical
